package br.com.battista.bgscore.constants;

public class CrashlyticsConstant {
    public static final String KEY_ACTIVITY = "Activity";
    public static final String KEY_OPEN_ACTIVITY = "Open Activity";

    public static final String KEY_FRAGMENT = "Fragment";
    public static final String KEY_OPEN_FRAGMENT = "Open Fragment";
    public static final String KEY_ACTION = "Action";

    public interface Actions {
        String ACTION_CLICK_MENU = "ActionClickMenu";
        String ACTION_CLICK_BUTTON = "ActionClickButton";
        String ACTION_EXIT = "ActionExit";
        String ACTION_OPEN = "ActionOpen";
        String ACTION_BACK = "ActionBack";
    }

    public interface ValueActions {
        String VALUE_BACK_HOME = "HOME";
        String VALUE_BACK_GAME = "GAME";
        String VALUE_BACK_MATCH = "MATCH";
        String VALUE_CLICK_MENU_HOME = "HOME";
        String VALUE_CLICK_MENU_MATCHES = "MATCHES";
        String VALUE_CLICK_MENU_GAMES = "GAMES";
        String VALUE_CLICK_MENU_PROFILE = "PROFILE";
        String VALUE_CLICK_MENU_INFO = "INFO";
        String VALUE_ACTION_EXIT = "EXIT";
        String VALUE_ACTION_OPEN = "OPEN";
        String VALUE_ACTION_CLICK_BUTTON_EXPORT_IMPORT_DATA = "EXPORT_IMPORT_DATA";
        String VALUE_ACTION_CLICK_BUTTON_CHANGE_AVATAR = "CHANGE_AVATAR";
        String VALUE_ACTION_CLICK_BUTTON_EDIT_PROFILE = "EDIT_PROFILE";
        String VALUE_ACTION_CLICK_BUTTON_ADD_FRIEND = "ADD_FRIEND";
        String VALUE_ACTION_CLICK_BUTTON_ADD_PLAYER = "ADD_PLAYER";
        String VALUE_ACTION_CLICK_BUTTON_LEGEND_GAME = "LEGEND_GAME";
        String VALUE_ACTION_CLICK_BUTTON_ADD_GAME = "ADD_GAME";
        String VALUE_ACTION_CLICK_BUTTON_ADD_GAME_ONLINE = "ADD_GAME_ONLINE";
        String VALUE_ACTION_CLICK_BUTTON_COPY_GAME = "COPY_GAME";
        String VALUE_ACTION_CLICK_BUTTON_EDIT_GAME = "EDIT_GAME";
        String VALUE_ACTION_CLICK_BUTTON_REMOVE_GAME = "REMOVE_GAME";
        String VALUE_ACTION_CLICK_BUTTON_OPEN_INFO_GAME = "OPEN_INFO_GAME";
        String VALUE_ACTION_CLICK_BUTTON_SORT_LIST_GAME = "SORT_LIST_GAME";
        String VALUE_ACTION_CLICK_BUTTON_SORT_LIST_MATCH = "SORT_LIST_MATCH";
        String VALUE_ACTION_CLICK_BUTTON_LEGEND_MATCH = "LEGEND_MATCH";
        String VALUE_ACTION_CLICK_BUTTON_ADD_MATCH = "ADD_MATCH";
        String VALUE_ACTION_CLICK_BUTTON_COPY_MATCH = "COPY_MATCH";
        String VALUE_ACTION_CLICK_BUTTON_EDIT_MATCH = "EDIT_MATCH";
        String VALUE_ACTION_CLICK_BUTTON_REMOVE_MATCH = "REMOVE_MATCH";
        String VALUE_ACTION_CLICK_BUTTON_DETAIL_MATCH = "DETAIL_MATCH";
        String VALUE_ACTION_CLICK_BUTTON_FINISH_MATCH = "FINISH_MATCH";
        String VALUE_ACTION_CLICK_BUTTON_SHARE_MATCH = "SHARE_MATCH";
        String VALUE_ACTION_CLICK_BUTTON_SHARE_MATCH_FULL = "SHARE_MATCH_FULL";
        String VALUE_ACTION_CLICK_BUTTON_LEGEND_RANKING_GAME = "LEGEND_RANKING_GAME";
    }

}
